import Image from 'next/image';
import { ArrowRight, BadgeCheck, Droplets, HeartHandshake, Microscope, ShieldCheck, Sparkles, Stethoscope } from 'lucide-react';
import BeforeAfter from '@/components/BeforeAfter';
import FAQ from '@/components/FAQ';
import FloatingWhatsApp from '@/components/FloatingWhatsApp';
import Header from '@/components/Header';
import Reveal from '@/components/Reveal';
import WhatsAppForm from '@/components/WhatsAppForm';

const benefits = [
  'Mejora visual significativa sin prometer eliminar la cicatriz.',
  'Resultados naturales integrados al tono de piel.',
  'Tratamientos personalizados según piel y cicatriz.',
  'Protocolos profesionales y pigmentos especializados.',
  'Recuperación de confianza y bienestar.'
];
const services = [
  { title: 'Cicatrices', icon: Microscope, text: 'Camuflaje de cicatrices quirúrgicas o traumáticas con un enfoque visualmente armónico.' },
  { title: 'Estrías', icon: Sparkles, text: 'Abordaje personalizado para mejorar la percepción visual de estrías localizadas.' },
  { title: 'Vitiligo localizado', icon: Droplets, text: 'Integración cromática cuidadosa para zonas específicas y seleccionadas.' },
  { title: 'Areola post mastectomía', icon: HeartHandshake, text: 'Reconstrucción óptica con sensibilidad estética y criterio profesional.' },
  { title: 'Camuflaje facial y corporal', icon: Stethoscope, text: 'Tratamientos diseñados para armonizar marcas visibles en distintas áreas.' }
];
const testimonials = [
  'Me sentí escuchada desde la valoración. El enfoque fue muy profesional y el resultado se ve armónico con mi piel.',
  'Agradecí mucho la explicación clara y el trato humano durante todo el proceso.',
  'Buscaba algo natural y discreto. La experiencia fue muy cuidadosa y personalizada.',
  'La valoración me transmitió confianza. Entendieron mi caso y me guiaron con realismo.',
  'Todo se sintió muy profesional, desde la atención hasta el seguimiento posterior.'
];

export default function HomePage() {
  const jsonLd = { '@context': 'https://schema.org', '@type': 'MedicalBusiness', name: 'Krása Dermoestudio', image: 'https://krasadermoestudio.vercel.app/og-image.jpg', telephone: '+50768917500', address: { '@type': 'PostalAddress', addressLocality: 'Panamá', addressCountry: 'PA' }, sameAs: ['https://instagram.com/krasadermoestudio'], url: 'https://krasadermoestudio.vercel.app' };
  return <main id="inicio"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Header /><FloatingWhatsApp />
  <section className="relative overflow-hidden pt-32"><div className="section-shell grid items-center gap-12 pb-16 pt-8 md:grid-cols-[1.1fr_0.9fr] md:pb-24 md:pt-14"><Reveal><div className="max-w-2xl"><span className="inline-flex rounded-full border border-black/10 bg-white/80 px-4 py-2 text-xs uppercase tracking-[0.22em] text-black/60">Dermopigmentación paramédica y estética avanzada</span><h1 className="mt-6 font-serif text-5xl leading-tight text-balance md:text-7xl">Recupera armonía visual en tu piel con un enfoque profesional y natural.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-black/68">Krása Dermoestudio combina conocimiento clínico de la piel, técnica artística avanzada y protocolos personalizados para valoración especializada en Panamá.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><a href="https://wa.me/50768917500?text=Hola%20Kr%C3%A1sa%20Dermoestudio%2C%20quisiera%20agendar%20una%20valoraci%C3%B3n." target="_blank" className="rounded-full bg-ink px-7 py-4 text-sm font-medium text-white transition hover:-translate-y-0.5">Agendar valoración por WhatsApp</a><a href="#resultados" className="rounded-full border border-black/10 bg-white px-7 py-4 text-sm font-medium text-black transition hover:-translate-y-0.5">Ver resultados</a></div><div className="mt-10 grid gap-4 sm:grid-cols-3">{['Con cita previa','Panamá','Atención personalizada'].map((item)=><div key={item} className="rounded-3xl border border-black/5 bg-white/70 px-4 py-4 text-sm text-black/70 shadow-soft">{item}</div>)}</div></div></Reveal><Reveal delay={0.15}><div className="card-premium relative overflow-hidden p-4 md:p-5"><div className="absolute inset-0 bg-soft-radial" /><div className="relative overflow-hidden rounded-[28px]"><Image src="/placeholders/hero.jpg" alt="Modelo de hero Krása Dermoestudio" width={900} height={1100} className="h-auto w-full object-cover" priority /></div><div className="relative mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-3xl border border-black/5 bg-white/80 p-4"><p className="text-xs uppercase tracking-[0.18em] text-black/50">Diferenciador</p><p className="mt-2 text-sm leading-6 text-black/70">Conocimiento clínico de la piel + técnica artística avanzada + protocolos personalizados.</p></div><div className="rounded-3xl border border-black/5 bg-white/80 p-4"><p className="text-xs uppercase tracking-[0.18em] text-black/50">Enfoque</p><p className="mt-2 text-sm leading-6 text-black/70">Resultados naturales, realistas y adaptados a cada caso.</p></div></div></div></Reveal></div></section>
  <section id="beneficios" className="py-16 md:py-24"><div className="section-shell"><Reveal><div className="max-w-2xl"><p className="text-sm uppercase tracking-[0.25em] text-black/45">Beneficios</p><h2 className="mt-4 font-serif text-4xl md:text-5xl">Una experiencia sobria, profesional y centrada en tu caso.</h2></div></Reveal><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-5">{benefits.map((item, index)=><Reveal key={item} delay={index * 0.06}><div className="card-premium h-full p-6"><BadgeCheck className="h-6 w-6 text-black/75" /><p className="mt-5 text-sm leading-7 text-black/72">{item}</p></div></Reveal>)}</div></div></section>
  <section className="py-16 md:py-24"><div className="section-shell grid gap-8 md:grid-cols-3">{[['1','Valoración profesional','Evaluación personalizada, tipo de piel y análisis del caso.'],['2','Estrategia de tratamiento','Se define el abordaje según zona, cicatriz y objetivo visual.'],['3','Procedimiento y seguimiento','Dermopigmentación paramédica con control posterior.']].map(([step, title, text], index)=><Reveal key={step} delay={index * 0.08}><div className="card-premium h-full p-8"><p className="text-sm uppercase tracking-[0.3em] text-black/45">Paso {step}</p><h3 className="mt-4 font-serif text-3xl">{title}</h3><p className="mt-4 leading-7 text-black/68">{text}</p></div></Reveal>)}</div></section>
  <section id="servicios" className="py-16 md:py-24"><div className="section-shell"><Reveal><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="text-sm uppercase tracking-[0.25em] text-black/45">Servicios</p><h2 className="mt-4 font-serif text-4xl md:text-5xl">Tratamientos enfocados en mejorar la apariencia visual con naturalidad.</h2></div><p className="max-w-md text-black/65">Evaluación profesional personalizada, diagnóstico de piel y cicatriz, estrategia de tratamiento, procedimiento y seguimiento.</p></div></Reveal><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{services.map((service, index)=>{const Icon = service.icon; return <Reveal key={service.title} delay={index * 0.06}><div className="card-premium h-full p-7 transition hover:-translate-y-1"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-cream"><Icon className="h-6 w-6 text-black/70" /></div><h3 className="mt-5 font-serif text-3xl">{service.title}</h3><p className="mt-4 leading-7 text-black/68">{service.text}</p></div></Reveal>;})}</div></div></section>
  <section id="resultados" className="py-16 md:py-24"><div className="section-shell"><Reveal><div className="max-w-2xl"><p className="text-sm uppercase tracking-[0.25em] text-black/45">Galería de resultados</p><h2 className="mt-4 font-serif text-4xl md:text-5xl">Antes y después con enfoque visual responsable.</h2><p className="mt-5 text-black/65">Las imágenes incluidas son placeholders. Reemplázalas en <code className="rounded bg-black/5 px-1.5 py-0.5">/public/placeholders</code>.</p></div></Reveal><div className="mt-10 grid gap-6 lg:grid-cols-[1.15fr_0.85fr]"><Reveal><BeforeAfter /></Reveal><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-1">{['gallery-1.jpg','gallery-2.jpg','gallery-3.jpg'].map((file, index)=><Reveal key={file} delay={index * 0.07}><div className="card-premium overflow-hidden p-3"><Image src={`/placeholders/${file}`} alt={`Ejemplo visual ${index + 1}`} width={900} height={700} className="rounded-[22px] object-cover" /></div></Reveal>)}</div></div></div></section>
  <section className="py-16 md:py-24"><div className="section-shell"><Reveal><div className="max-w-2xl"><p className="text-sm uppercase tracking-[0.25em] text-black/45">Testimonios</p><h2 className="mt-4 font-serif text-4xl md:text-5xl">Percepción humana, trato profesional y confianza.</h2><p className="mt-5 text-black/65">Amplia experiencia clínica. Testimonios de ejemplo con tono realista y sin claims médicos.</p></div></Reveal><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{testimonials.map((item, index)=><Reveal key={item} delay={index * 0.06}><div className="card-premium h-full p-7"><ShieldCheck className="h-6 w-6 text-black/65" /><p className="mt-5 leading-7 text-black/72">“{item}”</p><p className="mt-5 text-sm uppercase tracking-[0.2em] text-black/42">Paciente · Panamá</p></div></Reveal>)}</div></div></section>
  <section id="faq" className="py-16 md:py-24"><div className="section-shell grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><Reveal><div><p className="text-sm uppercase tracking-[0.25em] text-black/45">FAQ</p><h2 className="mt-4 font-serif text-4xl md:text-5xl">Respuestas claras antes de tu valoración.</h2><p className="mt-5 text-black/65">Sin promesas irreales, con información sobria y profesional.</p></div></Reveal><Reveal delay={0.1}><FAQ /></Reveal></div></section>
  <section id="contacto" className="py-16 md:py-24"><div className="section-shell grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><div><p className="text-sm uppercase tracking-[0.25em] text-black/45">Agenda tu valoración</p><h2 className="mt-4 font-serif text-4xl md:text-5xl">Conversemos sobre tu caso con un enfoque personalizado.</h2><p className="mt-5 text-black/65">Contacto principal: Luisana Concepción · Instagram: @krasadermoestudio · Ubicación: Panamá · Horario: Con cita previa.</p></div></Reveal><Reveal delay={0.1}><WhatsAppForm /></Reveal></div></section>
  <section className="pb-10 pt-4 md:pb-16"><div className="section-shell"><Reveal><div className="card-premium flex flex-col gap-6 p-8 md:flex-row md:items-center md:justify-between md:p-10"><div><p className="text-sm uppercase tracking-[0.24em] text-black/45">CTA final</p><h2 className="mt-3 font-serif text-3xl md:text-4xl">Agenda tu valoración por WhatsApp y recibe orientación inicial.</h2></div><a href="https://wa.me/50768917500?text=Hola%20Kr%C3%A1sa%20Dermoestudio%2C%20quisiera%20agendar%20una%20valoraci%C3%B3n." target="_blank" className="inline-flex items-center gap-2 rounded-full bg-ink px-7 py-4 text-sm font-medium text-white">Agendar valoración por WhatsApp <ArrowRight className="h-4 w-4" /></a></div></Reveal></div></section>
  <footer className="border-t border-black/5 py-10"><div className="section-shell flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><p className="font-serif text-2xl">Krása Dermoestudio</p><p className="mt-2 text-sm text-black/58">Panamá · Con cita previa · Instagram: @krasadermoestudio</p></div><p className="max-w-xl text-sm leading-6 text-black/52">Aviso legal: La información de este sitio es orientativa y no sustituye una valoración individual. Resultados pueden variar según cada caso.</p></div></footer></main>;
}
